import sys
from pathlib import Path

from test_mdd_best_config import main as run_best_config


def _prepend_defaults():
    root = Path(__file__).resolve().parent
    defaults = [
        "--data",
        "Mātai",
        "--data-path",
        str(root / "dataset" / "Mātai"),
        "--data-type",
        "TS",
        "--protocol",
        "AAL116",
        "--channel",
        "116",
        "--seq-len",
        "200",
        "--classes",
        "2",
        "--kfold",
        "5",
        "--max-folds",
        "5",
        "--iterations",
        "1",
        "--train-epochs",
        "70",
        "--batch-size",
        "8",
        "--learning-rate",
        "1e-3",
        "--d-model",
        "64",
        "--dropout",
        "0.1",
        "--time-series-harmonization",
        "none",
        "--module1-feature-mode",
        "alff",
        "--module1-temporal-dropout",
        "0.03",
        "--module1-roi-dropout",
        "0.02",
        "--use-deci-module1",
        "1",
        "--use-causal-module2",
        "1",
        "--use-hyperbolic-modules34",
        "1",
        "--causal-learning-target",
        "temporal_sem",
        "--classification-graph-source",
        "blend",
        "--module2-sample-correlation-blend",
        "0.75",
        "--hgcn-hidden-dim",
        "128",
        "--hgcn-dropout",
        "0.1",
        "--hpec-hgcn-logit-blend",
        "0.1",
        "--hpec-prototypes-per-class",
        "2",
        "--hpec-proto-temperature",
        "0.6",
        "--lambda-hpec-pcl",
        "0.0",
        "--lambda-hpec-pal",
        "0.0",
        "--lambda-hpec-hsic",
        "0.01",
        "--lambda-hpec-intra-orthogonal",
        "0.0",
        "--lambda-hpec-inter-margin",
        "0.02",
        "--lambda-hpec-energy-loss",
        "0.0",
        "--hpec-use-sinkhorn-ema",
        "1",
        "--hpec-ema-alpha",
        "0.995",
        "--hpec-ema-update-epochs",
        "5",
        "--hpec-trainable-prototypes",
        "0",
        "--print-metric-every",
        "10",
        "--print-data-info",
        "1",
        "--visualize-causal",
        "1",
        "--causal-vis-dir",
        "outputs/matai_best_config_causal",
        "--visualize-every",
        "0",
    ]
    sys.argv = [sys.argv[0], *defaults, *sys.argv[1:]]


if __name__ == "__main__":
    _prepend_defaults()
    run_best_config()
